スナイビーの実装
Vau1ters/air-po pull request #105
Opened 2020-08-23 09:01 UTC by poly65536

蜂

[TODO]
- [x] 弾の画像の設定

2020-09-06 04:52 UTC, Sobaya007 commented on src/core/entities/bulletFactory.ts
> +    const playerPosition = this.shooter.getComponent('Position')
playerPosition

2020-09-06 06:04 UTC, Sobaya007 approved these changes

2020-09-13 04:39 UTC, Vau1ters commented on src/core/components/bulletComponent.ts
>    private static readonly INITIAL_LIFE = 20
20回敵を貫通する？

2020-09-13 05:36 UTC, Vau1ters requested changes

2020-09-13 05:36 UTC, Vau1ters commented on src/core/entities/snibeeFactory.ts
> +  readonly CLIP_TOLERANCE_Y = 2
最大移動速度と同じにする

2020-09-13 06:49 UTC, Vau1ters requested changes

2020-09-13 08:38 UTC, Vau1ters approved these changes

2020-09-13 08:38 UTC, merged