効果音のテスト
Vau1ters/air-po pull request #114
Opened 2020-09-20 04:21 UTC by Uynet

Sound.play('ファイル名')で効果音が出るようになった

2020-09-20 09:54 UTC, Sobaya007 approved these changes

2020-09-20 10:02 UTC, Sobaya007 approved these changes

2020-09-27 04:57 UTC, poly65536 commented on package.json
> +    "semver": "^7.3.2",
semverとpackage-lock.json消してくれ～

2020-09-27 05:02 UTC, poly65536 requested changes
package-lock.json

2020-09-27 05:33 UTC, poly65536 commented on src/core/sound/sound.ts
> +export const init = (): void => {
async

2020-09-27 08:20 UTC, poly65536 approved these changes

2020-09-27 08:20 UTC, merged