こけ追加
Vau1ters/air-po pull request #118
Opened 2020-09-20 08:11 UTC by Sobaya007

2020-09-27 06:08 UTC, Vau1ters requested changes

2020-09-27 06:08 UTC, Vau1ters commented on src/core/entities/kokeFactory.ts
> +export class KokeFactory extends EntityFactory {
Mossにしなさい

2020-09-27 06:08 UTC, Vau1ters commented on src/core/graphics/art.ts
> +import kokeSetting from '../../../res/koke.json'
こいつらもMossに

2020-09-27 06:22 UTC, Vau1ters commented
こけの画像も後で追加する

2020-09-27 06:22 UTC, Vau1ters commented
明かりのつき方、消え方は後で調整する

2020-09-27 06:54 UTC, Vau1ters requested changes

2020-09-27 06:54 UTC, Vau1ters commented on res/shaders/darkness.frag
> +  float po = .1;
poって何

2020-09-27 06:54 UTC, Vau1ters commented on src/map/mapBuilder.ts
> +    kokePosition.y = y * th
多分ここもずれる

2020-09-27 06:54 UTC, Vau1ters commented on src/core/entities/kokeFactory.ts
> +    const airHolder = new AirHolderComponent({
なくてもできそう

2020-09-27 08:28 UTC, Sobaya007 commented on src/core/entities/kokeFactory.ts
> +export class KokeFactory extends EntityFactory {
難しい

2020-09-27 08:28 UTC, Sobaya007 commented on src/core/graphics/art.ts
> +import kokeSetting from '../../../res/koke.json'
しんどい

2020-09-27 08:31 UTC, Sobaya007 commented on res/shaders/darkness.frag
> +  float po = .1;
powerです

2020-09-27 08:39 UTC, Vau1ters commented on src/core/graphics/art.ts
> +import kokeSetting from '../../../res/koke.json'
:Ha:

2020-09-27 08:40 UTC, Vau1ters commented on res/shaders/darkness.frag
> +  float po = .1;
powerにしておいてください

2020-10-04 05:19 UTC, Vau1ters requested changes

2020-10-04 05:19 UTC, Vau1ters commented on res/shaders/darkness.frag
> +    if (length(coord - points[i].xy) < LIGHT_RADIUS) {
ここ

2020-10-04 05:21 UTC, Vau1ters approved these changes

2020-10-04 05:21 UTC, poly65536 commented on src/core/entities/category.ts
> +  SEARCH,
LIGHT_SEARCHの方が良くない？

2020-10-04 05:24 UTC, Sobaya007 commented on src/core/entities/category.ts
> +  SEARCH,
今後light以外にも使うくない？

2020-10-04 05:26 UTC, Sobaya007 commented on res/shaders/darkness.frag
> +    if (length(coord - points[i].xy) < LIGHT_RADIUS) {
だめ

2020-10-04 05:28 UTC, poly65536 commented on src/core/entities/category.ts
> +  SEARCH,
そうなんですか？

2020-10-04 05:29 UTC, poly65536 approved these changes

2020-10-04 05:42 UTC, merged