Fix: culling
Vau1ters/air-po pull request #144
Opened 2020-10-04 08:10 UTC by Sobaya007

2020-10-04 08:41 UTC, poly65536 approved these changes

2020-10-04 08:41 UTC, poly65536 commented on src/core/systems/drawSystem.ts
> +            -sw / 2 <= x + w / 2 && -sh / 2 <= y + h / 2 && x - w / 2 < sw / 2 && y - h / 2 < sh / 2
`w/2`じゃなくて`w * container.anchor.x`の方が正確そう

2020-10-04 08:41 UTC, poly65536 requested changes
a

2020-10-11 05:01 UTC, Vau1ters commented
正しくして

2020-10-11 06:04 UTC, poly65536 approved these changes
すぐ死にそうだけどとりあえずヨシ

2020-10-11 06:34 UTC, merged