レーザーサイトの実装
Vau1ters/air-po pull request #159
Opened 2020-10-18 05:53 UTC by poly65536

かっこいいレーザーサイト

2020-10-18 07:52 UTC, Sobaya007 commented
conflictしていますね笑

2020-10-18 08:27 UTC, Sobaya007 requested changes
BVHどうにかして

2020-10-18 08:27 UTC, Sobaya007 commented on src/core/components/bvhComponent.ts
> +  public queryRayMarch(ray: Ray, result: ReservedArray<[Collider, Vec2]>): void {
これはrayMarchではない

2020-10-25 06:59 UTC, Vau1ters requested changes

2020-10-25 06:59 UTC, Vau1ters commented on src/core/systems/uiSystem.ts
> +    })
farPointここでinitialValueとして追加して

2020-10-25 07:57 UTC, Sobaya007 approved these changes

2020-11-01 05:17 UTC, Vau1ters approved these changes

2020-11-01 05:18 UTC, merged