Feature/event sensor
Vau1ters/air-po pull request #161
Opened 2020-10-18 07:51 UTC by Sobaya007

close #156

2020-10-18 08:04 UTC, Vau1ters commented
コンフリクトしてますね笑

2020-10-18 09:56 UTC, Vau1ters requested changes

2020-10-18 09:56 UTC, Vau1ters commented on src/core/worlds/gameWorldFactory.ts
> +      return new GameWorldFactory().create(map, spawnerID) // eslint-disable-line  @typescript-eslint/no-use-before-define
ヤバそうなので別の実装を頼む

2020-10-25 05:54 UTC, Vau1ters commented on src/core/systems/drawSystem.ts
> +  public init(): void {
わからんのだけどthis.containerも初期化しなくて大丈夫？

2020-10-25 06:04 UTC, Vau1ters commented on src/core/systems/physicsSystem.ts
> +  }
init呼ばなくて大丈夫？

2020-10-25 08:04 UTC, Sobaya007 commented on src/core/systems/drawSystem.ts
> +  public init(): void {
containerは最初だけ初期化すればいいから大丈夫なはず

2020-10-25 08:07 UTC, Sobaya007 commented on src/core/systems/physicsSystem.ts
> +  }
initは勝手に呼ばれることにしてあるので、コンストラクタ内で呼ばないことにしている

2020-11-01 05:12 UTC, Vau1ters approved these changes

2020-11-01 05:45 UTC, poly65536 requested changes

2020-11-01 05:45 UTC, poly65536 commented on src/core/ecs/world.ts
> +    for (const entity of entities) {
これclearの前に持ってったらentitiesって変数いらなくない？

2020-11-01 05:45 UTC, poly65536 commented on src/core/entities/category.ts
> +      mask: new CategorySet(Category.ATTACK, Category.SENSOR),
hitBoxを乱用するのはやめたい

2020-11-01 05:45 UTC, poly65536 commented on src/core/entities/sensorFactory.ts
> +export class SensorFactory extends EntityFactory {
EventSensorにリネーム

2020-11-01 05:45 UTC, poly65536 commented on src/core/entities/sensorFactory.ts
> +  private h = 0
必須ではないけど、気持ち的に`position: Vec2`と`size: Vec2`感ある

2020-11-01 05:45 UTC, poly65536 commented on src/core/entities/sensorFactory.ts
> +  private event = ''
eventNameじゃね？

2020-11-01 05:45 UTC, poly65536 commented on src/core/systems/sensorSystem.ts
> +      case 'move':
moveだと座標移動の意味とかぶっちゃうから、moveMapとかchangeMapとかのほうが良さそう

2020-11-01 05:45 UTC, poly65536 commented on src/core/worlds/gameWorldFactory.ts
> +  public create(map: Map, playerSpanerID: number): World {
spawnerですよ笑

2020-11-01 05:50 UTC, poly65536 commented on src/map/mapBuilder.ts
> +    for (const { x, y, width, height, properties } of playerLayer.objects) {
forで回すんじゃなくてfindして存在することをassertした方が良くない？

2020-11-01 06:02 UTC, Sobaya007 commented on src/core/entities/sensorFactory.ts
> +  private event = ''
```typescript
event = `${eventName} ${options}`
```
なのでこうした

2020-11-01 06:02 UTC, Sobaya007 commented on src/core/ecs/world.ts
> +    for (const entity of entities) {
コメントの通りなので却下

2020-11-01 06:14 UTC, poly65536 approved these changes

2020-11-01 06:14 UTC, merged