Modify: enemy1
Vau1ters/air-po pull request #170
Opened 2020-11-08 07:25 UTC by Sobaya007

- change image
- change behaviour
  - add idle state
  - fix walk speed
- change animation system

2020-11-08 08:04 UTC, poly65536 commented on src/game/ai/entity/common/action/animate.ts
> +  while (!animation.playing) yield
ここのコード深すぎて一瞬わからなかったからコメント入れたほうが良いかもしれん

2020-11-08 08:04 UTC, poly65536 commented on src/game/ai/entity/common/action/animate.ts
> +  const [child] = entity.getComponent('Draw').children
AnimationStateComponentにアニメーションするcontainer打ち込んだほうが良いかも

2020-11-08 08:04 UTC, poly65536 commented on src/game/ai/entity/enemy1/enemy1AI.ts
> +    for (let i = 0; i < 3; i++) yield* animate(entity, 'Idle')
これでも良いけど、animateの引数に繰り返し回数を取っても良いかもしれないと思った。異論は認める。

2020-11-08 10:35 UTC, Sobaya007 commented on src/game/ai/entity/common/action/animate.ts
> +  while (!animation.playing) yield
深い

2020-11-08 10:36 UTC, Sobaya007 commented on src/game/ai/entity/enemy1/enemy1AI.ts
> +    for (let i = 0; i < 3; i++) yield* animate(entity, 'Idle')
やだ

2020-11-15 05:33 UTC, Vau1ters requested changes

2020-11-15 05:33 UTC, Vau1ters commented on src/game/components/animationStateComponent.ts
> +    this.changeState.notify(value)
if(value != this._state)消して大丈夫なやつ？

2020-11-15 05:33 UTC, Vau1ters commented on src/game/ai/entity/enemy1/enemy1AI.ts
> +  yield* animate(entity, 'Dying')
animationSpeed = 0.2で

2020-11-15 08:06 UTC, poly65536 approved these changes

2020-11-22 04:29 UTC, Sobaya007 commented on src/game/components/animationStateComponent.ts
> +    this.changeState.notify(value)
逆に消さなきゃだめだった気がする

2020-11-29 07:53 UTC, Vau1ters approved these changes

2020-11-29 08:30 UTC, merged