装備（空気タンク）の追加
Vau1ters/air-po pull request #176
Opened 2020-11-22 07:12 UTC by poly65536

空気タンク実装
close: https://github.com/Vau1ters/air-po/issues/173

- プレイヤーの装備として実装
- マップ内に出現するアイテムとして実装

2020-11-29 04:03 UTC, Sobaya007 approved these changes

2020-11-29 08:14 UTC, Vau1ters approved these changes

2020-12-06 06:36 UTC, Sobaya007 requested changes
仕様変更したのでこのPR自体どうなん？

2020-12-13 04:16 UTC, Sobaya007 approved these changes
とりあえずヨシ！

2020-12-13 05:30 UTC, merged