コマンドを叩くとartにimport文とtextureStoreへの参照を追加するスクリプト
Vau1ters/air-po pull request #187
Opened 2020-12-06 08:57 UTC by Uynet

2020-12-06 13:50 UTC, Sobaya007 commented
close #182

2020-12-13 10:33 UTC, Vau1ters commented
soundtoolっぽく書いて

2020-12-13 14:30 UTC, Uynet commented
全体的に書き換えて比較的読みやすくしました

2020-12-13 15:29 UTC, Uynet commented
現状res/map下のステージファイルと設定ファイルを区別する手段がないため不要なファイルをimportしてしまうのですが、ファイル名だけで判別するのは煩雑になりそうなためディレクトリごと分けるか不要importを許容する方針として別issueにしたいです

2020-12-20 09:00 UTC, Vau1ters requested changes

2020-12-20 09:00 UTC, Vau1ters commented on arttool.ts
> +    `buildAnimationTexture(${camelFilename}Img, ${camelFilename}Setting`
ここも変わる

2020-12-20 09:49 UTC, Uynet commented on soundtool.ts
> +console.log("unko")
けした

2020-12-20 09:49 UTC, Uynet commented on arttool.ts
> +    `buildAnimationTexture(${camelFilename}Img, ${camelFilename}Setting`
fix

2020-12-20 09:49 UTC, Uynet commented on arttool.ts
> +  const loadReg = new RegExp('buildSingleTexture\\(' + `${camelFilename}Img`)
fix

2021-02-07 08:37 UTC, poly65536 commented on arttool.ts
> +const importReg = new RegExp('// IMPORT')
よく考えたらこれ正規表現で置換するんじゃなくて、`fileText`を関数にして引数に取れるようにしたほうが良いんじゃね

2021-02-07 08:37 UTC, poly65536 commented on arttool.ts
> +function loadTexture(url: string): Promise<BaseTexture> {
せっかくだし`function`じゃなくてアロー関数に書き換えて星

2021-02-07 08:37 UTC, poly65536 commented on arttool.ts
> +  const ext = e.name.split('.')[1]
``` javascript
const [filename, ext] = e.name.split('.')
```
で書ける

2021-02-07 08:37 UTC, poly65536 commented on arttool.ts
> +  const ext = e.name.split('.')[1]
ここも

2021-02-07 11:12 UTC, Uynet commented on arttool.ts
> +const importReg = new RegExp('// IMPORT')
これよくわからなかったのでもうちょっと詳細な説明ください

2021-02-07 11:13 UTC, Uynet commented on arttool.ts
> +  const ext = e.name.split('.')[1]
神

2021-02-07 11:13 UTC, Uynet commented on arttool.ts
> +  const ext = e.name.split('.')[1]
done

2021-02-07 11:13 UTC, Uynet commented on arttool.ts
> +function loadTexture(url: string): Promise<BaseTexture> {
done

2021-02-14 05:28 UTC, poly65536 commented on arttool.ts
> +function loadTexture(url: string): Promise<BaseTexture> {
pushされてなくないwow wow

2021-02-14 05:32 UTC, poly65536 commented on arttool.ts
> +const importReg = new RegExp('// IMPORT')
いま`// IMPORT`とかを正規表現で置き換えてるけど、そうじゃなくて
``` javascript
const fileText = (importTexts: string, loadImgTexts: string): string => `
  ${importTexts}
  ...
  ${loadImgTexts}
  ...
`
```
みたいに書けないかなっていう

2021-02-14 06:35 UTC, Uynet commented on arttool.ts
> +const importReg = new RegExp('// IMPORT')
その説もあるけど、あんま変更する必要も無い気がする

2021-02-14 08:28 UTC, poly65536 approved these changes

2021-02-14 08:30 UTC, Vau1ters approved these changes

2021-02-14 08:36 UTC, merged