Add: Fukidashi
Vau1ters/air-po pull request #188
Opened 2020-12-11 18:21 UTC by Sobaya007

2021-02-14 09:36 UTC, Vau1ters requested changes

2021-02-14 09:36 UTC, Vau1ters commented on res/shaders/fukidashi.frag
> +precision highp float;
ファイル名を日本語にしない

2021-02-14 09:36 UTC, Vau1ters commented on res/shaders/fukidashi.vert
> +attribute vec2 aVertexPosition;
日本語にしない

2021-02-14 09:40 UTC, poly65536 commented on src/game/ai/entity/fukidashi/fukidashiAI.ts
> +  yield
このyieldなに

2021-02-14 09:58 UTC, Vau1ters requested changes

2021-02-14 09:58 UTC, Vau1ters commented on res/shaders/fukidashiText.frag
> +varying vec2 vTextureCoord;
ファイル名

2021-02-14 09:58 UTC, Vau1ters commented on src/game/ai/entity/fukidashi/fukidashiAI.ts
> +const chase = function*(fukidashi: Entity, target: Entity, camera: Entity): Behaviour<void> {
日本語

2021-02-14 09:58 UTC, Vau1ters commented on src/game/ai/entity/fukidashi/fukidashiAI.ts
> +const chase = function*(fukidashi: Entity, target: Entity, camera: Entity): Behaviour<void> {
Speech Balloonにしてください

2021-02-21 05:24 UTC, poly65536 commented
known issue:
吹き出しに改行無しで長い文章を設定すると、文章が吹き出しからはみ出る。PIXI.Textならword wrapの設定ができるが、PIXI.BitmapTextには対処する方法がなさそう。プログラム側で頑張って修正するか、設定する文章側で対処するか要議論。

2021-02-25 11:33 UTC, Sobaya007 commented
> known issue:
> 吹き出しに改行無しで長い文章を設定すると、文章が吹き出しからはみ出る。PIXI.Textならword wrapの設定ができるが、PIXI.BitmapTextには対処する方法がなさそう。プログラム側で頑張って修正するか、設定する文章側で対処するか要議論。

とりあえずよくない？

2021-03-14 04:09 UTC, poly65536 requested changes

2021-03-14 04:09 UTC, poly65536 commented on src/game/ai/entity/player/playerTalk.ts
> +import { Behaviour } from '@core/behaviour/behaviour'
デバッグ用のコマンドはどっかに隔離したい感

2021-03-14 05:02 UTC, Vau1ters commented
僕のフォント使ってほしい

2021-03-14 08:20 UTC, Sobaya007 commented
- フォント画像
- フォント画像内の文字列

があればいける

2021-03-21 05:40 UTC, poly65536 approved these changes

2021-03-21 05:41 UTC, Vau1ters approved these changes

2021-03-21 05:41 UTC, merged