Soundtool
Vau1ters/air-po pull request #192
Opened 2020-12-13 08:56 UTC by Uynet

## how to use
1.効果音ファイルをres/soundに追加する(wavのみ)
2.`yarn soundtool`を実行
3.src/core.sound/sound.tsが書き換わり、ファイル名と同じオブジェクトが追加される

2020-12-13 10:32 UTC, Vau1ters requested changes

2020-12-13 10:32 UTC, Vau1ters commented on src/core/sound/sound.ts
> +// IMPORT
自動生成されていることを書く

2020-12-13 14:29 UTC, Uynet commented on src/core/sound/sound.ts
> +// IMPORT
書いた

2020-12-20 06:43 UTC, Vau1ters approved these changes

2020-12-20 08:49 UTC, poly65536 commented on soundtool.ts
> +  generatedText = generatedText.replace(importReg, `// IMPORT\n${importText(filename)}`)
reduceして最後にまとめて置換したほうが綺麗だと思った。そうすれば`generatedText`を`let`にする必要もなくなると思う。

2020-12-20 08:49 UTC, poly65536 commented on soundtool.ts
> +const notificationText = `/*+.† NOTIFICATION †.+*/
これ`fileText`に元から書くのはだめなん？

2020-12-20 08:49 UTC, poly65536 commented on soundtool.ts
> +import * as fs from 'fs'
プログラム実行時にログを吐いたほうが精神衛生上良いことが知られている。

2020-12-20 08:49 UTC, poly65536 requested changes
po

2020-12-20 09:09 UTC, Uynet commented on soundtool.ts
> +const notificationText = `/*+.† NOTIFICATION †.+*/
fix

2020-12-20 09:12 UTC, Uynet commented on soundtool.ts
> +  generatedText = generatedText.replace(importReg, `// IMPORT\n${importText(filename)}`)
fix

2020-12-20 09:26 UTC, poly65536 commented on soundtool.ts
> +function importText(filename: string): string {
arrowにして

2020-12-20 09:34 UTC, Uynet commented on soundtool.ts
> +function importText(filename: string): string {
arrowed

2020-12-20 09:34 UTC, Uynet commented on soundtool.ts
> +import * as fs from 'fs'
logged

2020-12-20 09:45 UTC, poly65536 approved these changes

2020-12-20 09:45 UTC, merged