スナイビー死亡モーション
Vau1ters/air-po pull request #195
Opened 2020-12-20 09:25 UTC by Vau1ters

画面共有で見ても分かりづらいと思うので実際に動かして見てほしい
音もつけたい

2021-02-07 04:20 UTC, poly65536 requested changes

2021-02-07 04:20 UTC, poly65536 commented on src/game/ai/entity/snibee/snibeeAI.ts
> +  for (let i = 0; i < 20; i++) yield
`wait`みたいな関数があったはず

2021-02-07 04:20 UTC, poly65536 commented on src/game/ai/entity/snibee/snibeeAI.ts
> +    animateLoop(entity, 'Alive', 0.3),
#196 で変わるから合わせてほしい

2021-02-14 10:25 UTC, Vau1ters commented on src/game/ai/entity/snibee/snibeeAI.ts
> +    animateLoop(entity, 'Alive', 0.3),
合わせた（はず）

2021-02-14 10:25 UTC, Vau1ters commented on src/game/ai/entity/snibee/snibeeAI.ts
> +  for (let i = 0; i < 20; i++) yield
消えた

2021-02-21 05:19 UTC, poly65536 commented on src/game/ai/entity/snibee/snibeeAI.ts
> +  for (let x = 0; x < 10; x++) {
ここもっとうまく書きたみがある

2021-03-18 06:27 UTC, Sobaya007 commented
これ消えるときパッと消えるけどいいの？

2021-03-28 05:26 UTC, poly65536 approved these changes

2021-04-04 06:52 UTC, merged