feature/lockのリファクタ案
Vau1ters/air-po pull request #255
Opened 2021-04-13 04:03 UTC by poly65536

ロックの状態管理をシンプルにしたかった

あとレーザーが地面貫通してたのでもとの仕様に直した

2021-04-13 11:22 UTC, Sobaya007 requested changes

2021-04-13 11:22 UTC, Sobaya007 commented on src/game/ai/entity/laserSight/laserSightAI.ts
> +  for (const state of getLaserSightState) {
ここ上とくっつけていい気がする
```typescript 
for (const state of getLaserSightStateGenerator(player, laser, world))
```

2021-04-13 14:18 UTC, poly65536 commented on src/game/ai/entity/laserSight/laserSightAI.ts
> +      const { value } = getClosestHit.next()
最初そうしてたんだけど、
```javascript
for (const po of generator) {
  if (...) return
  ...
}
```
って書くと、`return`のタイミングでなぜか`generator`がcloseされるのでこう書いた。謎すぎるけど仕様確認しないと詳しいことはわからん。なんか情報あったら教えて

2021-04-13 14:18 UTC, poly65536 commented on src/game/ai/entity/laserSight/laserSightAI.ts
> +      const { value } = getClosestHit.next()
ditto

2021-04-13 14:26 UTC, poly65536 commented on src/game/ai/entity/laserSight/laserSightAI.ts
> +    !MouseController.isMousePressing('Right')
そういうのはコメントの役割な気もするし、今回は特に情報が隔離されてるしそこまでしなくても良さそうだと思った

2021-04-13 14:30 UTC, poly65536 commented on src/game/ai/entity/laserSight/laserSightAI.ts
> +    !MouseController.isMousePressing('Right')
コメントに書いたらキモくなったのでやっぱそばや案で行くわ

2021-04-14 12:30 UTC, Sobaya007 commented on src/game/ai/entity/laserSight/laserSightAI.ts
> +      const { value } = getClosestHit.next()
これ多分`getCloseHit`を変数に分離しているのが原因だと思う。
```typescript
for (const { entity, point } of getClosestHitGenerator(player, laser))
```
にしたらいけるしそれでよくない？

2021-04-18 04:22 UTC, poly65536 commented on src/game/ai/entity/laserSight/laserSightAI.ts
> +      const { value } = getClosestHit.next()
`hitInfo`の状態管理がおかしくなるのでダメです

2021-04-18 04:24 UTC, Sobaya007 requested changes

2021-04-18 07:31 UTC, Sobaya007 approved these changes

2021-04-18 07:31 UTC, merged