拝啓
Vau1ters/air-po pull request #281
Opened 2021-05-30 04:04 UTC by poly65536

2021-06-27 05:42 UTC, Sobaya007 requested changes
#274 を含めてほしい

2021-07-04 05:30 UTC, poly65536 commented
https://doc.mapeditor.org/en/stable/manual/layers/#image-layers

2021-07-04 10:14 UTC, Sobaya007 requested changes
HorizonをEntityにしたくない

2021-07-04 10:14 UTC, Sobaya007 commented on src/game/systems/backgroundSystem.ts
> +    for (const camera of this.cameraFamily.entityIterator) {
singletonであることを明記するために
```javascript
const [camera] = this.cameraFactory.entityArray
```
みたいにしたい

2021-07-11 10:19 UTC, Sobaya007 requested changes

2021-07-18 03:51 UTC, Sobaya007 approved these changes

2021-07-18 04:09 UTC, merged