[WIP]キノコのアニメーション追加
Vau1ters/air-po pull request #287
Opened 2021-06-20 10:20 UTC by Vau1ters

2021-06-20 10:21 UTC, Vau1ters commented
胞子を横に出す
EaseOutする

2021-06-27 05:20 UTC, Vau1ters commented
↑やめた

2021-06-27 07:51 UTC, Sobaya007 requested changes

2021-06-27 07:51 UTC, Sobaya007 commented on src/game/entities/effect/sporeEffectFactory.ts
> +  }
ここに空行ほしい

2021-06-27 07:51 UTC, Sobaya007 commented on src/game/components/mushroomComponent.ts
> +  constructor(public landed = false) {}
これ消せない？

2021-06-27 08:13 UTC, poly65536 requested changes

2021-06-27 08:13 UTC, poly65536 commented on src/game/ai/entity/mushroom/mushroomAI.ts
>        yield* animate({ entity, state: 'Close' })
一応`opened`を`false`にしといたほうが良さそう

2021-06-27 08:13 UTC, poly65536 commented on src/game/ai/entity/mushroom/mushroomAI.ts
> +      } else if (opened) {
これ
``` typescript
for (...) sporeFactory.create()
yield* animate(Opening)
while(hasAir) animate(Open)
```
みたいに書けない？

2021-06-27 09:04 UTC, Vau1ters commented on src/game/ai/entity/mushroom/mushroomAI.ts
> +          sporeFactory.setPosition(
i使いたいので微妙

2021-06-27 09:10 UTC, Vau1ters commented on src/game/ai/entity/mushroom/mushroomAI.ts
>        yield* animate({ entity, state: 'Close' })
一度開いたら閉じることはないけどfalseにしておいた

2021-06-27 10:01 UTC, Vau1ters commented on src/game/ai/entity/mushroom/mushroomAI.ts
>        yield* animate({ entity, state: 'Close' })
コード直したらいらんくなった

2021-06-27 10:01 UTC, Vau1ters commented on src/game/ai/entity/mushroom/mushroomAI.ts
> +      } else if (opened) {
みたいに書いた

2021-06-27 10:01 UTC, Vau1ters commented on src/game/components/mushroomComponent.ts
> +  constructor(public landed = false) {}
消した

2021-06-27 10:02 UTC, Vau1ters commented on src/game/entities/effect/sporeEffectFactory.ts
> +  }
入れた

2021-06-27 10:08 UTC, Vau1ters commented on res/map/tileset/spore.json
> +{ "columns":6,
消した

2021-06-27 14:40 UTC, poly65536 commented on src/game/ai/entity/mushroom/mushroomAI.ts
> +    return !hasAir(entity)()
ワンチャン`not`作って`suspendable(not(hasAir(entity)), ...)`みたいに書けたほうが便利かも

2021-06-27 14:41 UTC, poly65536 commented on src/game/ai/entity/mushroom/mushroomAI.ts
> +          sporeFactory.setPosition(
`sporeFactory.setPosition(position, i)`みたいに書けるようにすればいけそうじゃない？

2021-06-27 14:42 UTC, poly65536 commented on src/game/ai/entity/mushroom/mushroomAI.ts
> +      } else if (opened) {
天才

2021-07-04 04:23 UTC, Sobaya007 requested changes

2021-07-04 04:23 UTC, Sobaya007 commented on src/game/ai/entity/player/playerJet.ts
> +import { JetEffectFactory } from '@game/entities/effect/jetEffectFactory'
謎diff

2021-07-04 04:46 UTC, Sobaya007 approved these changes

2021-07-04 04:48 UTC, poly65536 commented on src/game/ai/entity/mushroom/mushroomAI.ts
> +          sporeFactory.setPosition(
どっちでもよいということになった

2021-07-04 04:56 UTC, poly65536 approved these changes

2021-07-04 04:56 UTC, merged