Feature/sound panning
Vau1ters/air-po pull request #303
Opened 2021-07-11 07:39 UTC by Sobaya007

close #300, #283, #198, #197

2021-07-11 08:44 UTC, poly65536 commented on src/game/components/soundComponent.ts
> +export type Sound = {
`SoundInstance`にまとめて良さそう

2021-07-11 09:41 UTC, poly65536 approved these changes

2021-07-11 10:53 UTC, poly65536 requested changes
銃声が二重に（？）聞こえている気がする

2021-07-18 03:27 UTC, Sobaya007 commented
二重音声問題、私はやっぱりよくわからん

2021-07-18 03:48 UTC, poly65536 approved these changes

2021-07-18 03:48 UTC, merged