爆発アニメ遅いのを修正
Vau1ters/air-po pull request #448
Opened 2022-03-27 05:41 UTC by Vau1ters

絵を変えただけ

2022-03-27 09:29 UTC, poly65536 approved these changes

2022-04-03 04:20 UTC, poly65536 requested changes
po

2022-04-10 05:06 UTC, Vau1ters commented
爆発エフェクトとかつけていい感じにした

2022-04-10 08:22 UTC, poly65536 approved these changes

2022-04-17 08:30 UTC, merged